[tool.ruff]
target-version = "py311"

exclude = [
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN",
    "D",
    "EM101",
    "S105",
    "RUF012",
    "N80",
    "PT00",
    "TRY003",
    "S101",
]
