# Generated by Django 5.0.2 on 2024-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccountTransfersRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.TextField()),
                ("organization_iban", models.TextField()),
                ("organization_bic", models.TextField()),
            ],
        ),
    ]
