# Generated by Django 5.0.2 on 2024-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.TextField()),
                ("balance_cents", models.IntegerField()),
                ("iban", models.TextField(unique=True)),
                ("bic", models.TextField(unique=True)),
            ],
        ),
    ]
