# Generated by Django 5.0.2 on 2024-02-21 14:11

from django.db import migrations


def add_bank_account(apps, _):
    BankAccount = apps.get_model("bank_accounts", "BankAccount")
    bank_account = BankAccount(
        organization_name="ACME Corp",
        bic="OIVUSCLQXXX",
        iban="FR10474608000002006107XXXXX",
        balance_cents=7777777,
    )
    bank_account.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bank_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_bank_account),
    ]
