# Generated by Django 5.0.2 on 2024-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_accounts", "0002_auto_20240221_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="balance_cents",
            field=models.PositiveIntegerField(),
        ),
    ]
