# Generated by Django 5.0.2 on 2024-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0002_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="amount_cents",
            field=models.PositiveIntegerField(),
        ),
    ]
