# Generated by Django 5.0.2 on 2024-02-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_account_transfers", "0001_initial"),
        ("transfers", "0003_alter_transfer_amount_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="bank_account_transfers_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank_account_transfers.bankaccounttransfersrequest",
            ),
        ),
    ]
