# Generated by Django 5.0.2 on 2024-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0004_transfer_bank_account_transfers_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="amount_cents",
            field=models.PositiveBigIntegerField(),
        ),
    ]
